# Generated by Django 3.1 on 2022-10-16 17:47

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('nombre_empresa', models.CharField(max_length=100, unique=True)),
                ('direccion_empresa', models.TextField()),
                ('registro_empresa', models.CharField(max_length=100, unique=True)),
                ('telefono_empresa', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cliente.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='empresa.clienteempresa')),
            ],
            options={
                'abstract': False,
            },
            bases=('cliente.cliente',),
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
    ]
